### ISSUE TITLE
https://askubuntu.com/questions/1392531/how-can-i-view-my-wyze-camera-live-video-stream-on-linux-ubuntu

### ISSUE THREAD

**Issue by famewolf** [CoconutMacaroon/Hangman#20]
HI,
Apologies for putting this here.  I could not find another way to contact you.

Thanks for your detailed answer on getting wyze running on android-x86 in virtualbox.  I'm wondering did you actually open the app and have it working because I just followed your instructions using the same iso  and the wyze app crashes as soon as it' opens....I noticed all it's permissions were set to denied and allowed all of them but it still crashes. 

![image](https://user-images.githubusercontent.com/4558832/185751164-873c0f79-d82d-4e82-bf71-ebf6cb267644.png)

I also noted there does not appear to be a way to make it full screen?  Finally almost everything refuses to update because it tells me that google play services needs to be updated but when I go to google play services in the list of apps it doesn't show update as an option?

Thanks for your time!

Rudi Pittman

**Comment by CoconutMacaroon** [comment]
@famewolf I posted that answer a while ago, I don't recall exactly how much I tested it. Regardless, I suggest reading [the other answer](https://askubuntu.com/a/1392626/1438484), and part of that may work. Also check out [this question](https://askubuntu.com/questions/1392621/which-android-emulators-or-android-virtual-machines-run-well-on-ubuntu-18-04-and). If neither of those work, go ahead and [post a new question](https://askubuntu.com/questions/ask) with the steps you took, and what didn't work, and then you might get an answer there
